name: Strato SFTP Deployment

on:
  push:
    branches:
      - main  # Prüfe, ob dein Haupt-Branch bei GitHub wirklich 'main' heißt

jobs:
  web-deploy:
    name: 🚀 Deploy to Strato
    runs-on: ubuntu-latest
    steps:
    
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: 📂 Sync files to Strato
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        # Wir nutzen jetzt genau die Daten, die in FileZilla funktioniert haben
        server: 5020282487.ssh.w2.strato.hosting
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        protocol: sftp
        
        local-dir: ./
        server-dir: ./
        delete-clean: false # Setze auf 'true', wenn Dateien auf Strato gelöscht werden sollen, die nicht in GitHub sind
