name: Strato Deployment

on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🚀 Deploy Website to Strato via SCP
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Upload files to Strato
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 5020282487.ssh.w2.strato.hosting
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22
          source: "./*"
          target: "/"
          overwrite: true
          strip_components: 1
